apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "watch-rayjob-app-chart.fullname" . }}-config
  labels:
    {{- include "watch-rayjob-app-chart.labels" . | nindent 4 }}
data:
  SQLITE_PATH: {{ .Values.config.sqlitePath | quote }}
  KUBERAY_API_SERVER: {{ .Values.config.kuberayApiServer | quote }}
  POLL_INTERVAL: {{ .Values.poller.intervalSeconds | quote }}