name: Docker Image CI on Release

# This workflow now runs only when a new release is created in GitHub
on:
  release:
    types: [created]

env:
  # Set your full Docker image repository name.
  IMAGE_REPO: flavio185/fastapi-duckdb-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract release version
        id: get_version
        # This command gets the tag of the release that triggered the workflow (e.g., "v1.0.0")
        # and saves it into an environment variable named VERSION.
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.VERSION }}
